# Generated by Django 5.2.16 on 2026-09-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='workorders__custome_f091b7_idx',
            old_name='workorders__custome_2d63e8_idx',
        ),
        migrations.RenameIndex(
            model_name='servicerequest',
            new_name='workorders__status_ae0bd7_idx',
            old_name='workorders__status_6cc7ad_idx',
        ),
    ]
