# Generated by Django 5.2.16 on 2026-09-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_owner_i_668a2a_idx',
            old_name='services_se_owner_i_6c8a9e_idx',
        ),
        migrations.RenameIndex(
            model_name='service',
            new_name='services_se_name_32d28c_idx',
            old_name='services_se_name_1c2d8d_idx',
        ),
    ]
