# Generated by Django 5.2.16 on 2026-09-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_878a13_idx',
            old_name='notificatio_user_id_6a0f7c_idx',
        ),
    ]
